[[runs]]
Id = "rust-master x rust-v0.47.0 : tcp"
transport = "tcp"

  [[runs.groups]]
  Id = "rust-master.tcp"

    [runs.groups.instances]
    count = 1

    [runs.groups.test_params]
    transport = "tcp"

  [[runs.groups]]
  Id = "rust-v0.47.0.tcp"

    [runs.groups.instances]
    count = 1

    [runs.groups.test_params]
    transport = "tcp"

[[runs]]
Id = "rust-master x go-master : tcp"
transport = "tcp"

  [[runs.groups]]
  Id = "rust-master.tcp"

    [runs.groups.instances]
    count = 1

    [runs.groups.test_params]
    transport = "tcp"

  [[runs.groups]]
  Id = "go-master.tcp"

    [runs.groups.instances]
    count = 1

    [runs.groups.test_params]
    transport = "tcp"

[[runs]]
Id = "rust-master x go-v0.22 : tcp"
transport = "tcp"

  [[runs.groups]]
  Id = "rust-master.tcp"

    [runs.groups.instances]
    count = 1

    [runs.groups.test_params]
    transport = "tcp"

  [[runs.groups]]
  Id = "go-v0.22.tcp"

    [runs.groups.instances]
    count = 1

    [runs.groups.test_params]
    transport = "tcp"

[[runs]]
Id = "rust-v0.47.0 x go-master : tcp"
transport = "tcp"

  [[runs.groups]]
  Id = "rust-v0.47.0.tcp"

    [runs.groups.instances]
    count = 1

    [runs.groups.test_params]
    transport = "tcp"

  [[runs.groups]]
  Id = "go-master.tcp"

    [runs.groups.instances]
    count = 1

    [runs.groups.test_params]
    transport = "tcp"

[[runs]]
Id = "rust-v0.47.0 x go-v0.22 : tcp"
transport = "tcp"

  [[runs.groups]]
  Id = "rust-v0.47.0.tcp"

    [runs.groups.instances]
    count = 1

    [runs.groups.test_params]
    transport = "tcp"

  [[runs.groups]]
  Id = "go-v0.22.tcp"

    [runs.groups.instances]
    count = 1

    [runs.groups.test_params]
    transport = "tcp"

[[runs]]
Id = "go-master x go-v0.22 : tcp"
transport = "tcp"

  [[runs.groups]]
  Id = "go-master.tcp"

    [runs.groups.instances]
    count = 1

    [runs.groups.test_params]
    transport = "tcp"

  [[runs.groups]]
  Id = "go-v0.22.tcp"

    [runs.groups.instances]
    count = 1

    [runs.groups.test_params]
    transport = "tcp"

[[runs]]
Id = "go-ckousik x anotherwebrtc : webrtc"
transport = "webrtc"

  [[runs.groups]]
  Id = "go-ckousik.webrtc"

    [runs.groups.instances]
    count = 1

    [runs.groups.test_params]
    transport = "webrtc"

  [[runs.groups]]
  Id = "anotherwebrtc.webrtc"

    [runs.groups.instances]
    count = 1

    [runs.groups.test_params]
    transport = "webrtc"

[[instances]]
Id = "rust-master.tcp"
Version = "0.48.0"
IsMaster = true
Implementation = "rust"
CargoFeatures = "libp2pmaster"
SupportedTransports = [ "tcp" ]
transport = "tcp"

[[instances]]
Id = "rust-v0.47.0.tcp"
Version = "0.47.0"
Implementation = "rust"
CargoFeatures = "libp2pv0470"
SupportedTransports = [ "tcp" ]
transport = "tcp"

[[instances]]
Id = "go-master.tcp"
GoVersion = "1.18"
IsMaster = true
Modfile = "go.v0.22.mod"
Implementation = "go"
Selector = "v0.22"
SupportedTransports = [ "tcp" ]
transport = "tcp"

[[instances]]
Id = "go-v0.22.tcp"
GoVersion = "1.18"
Modfile = "go.v0.22.mod"
Implementation = "go"
Selector = "v0.22"
SupportedTransports = [ "tcp" ]
transport = "tcp"

[[instances]]
Id = "go-ckousik.webrtc"
GoVersion = "1.18"
Modfile = "go.ckousik.mod"
Implementation = "go"
Repository = "https://github.com/ckousik/go-libp2p.git"
Branch = "ckousik/webrtc"
Selector = "ckousik"
SupportedTransports = [ "webrtc" ]
transport = "webrtc"

[[instances]]
Id = "anotherwebrtc.webrtc"
GoVersion = "1.18"
Modfile = "go.ckousik.mod"
Implementation = "go"
Repository = "https://github.com/ckousik/go-libp2p.git"
Branch = "ckousik/webrtc"
Selector = "ckousik"
SupportedTransports = [ "webrtc" ]
transport = "webrtc"
