[metadata]
  name = "test-interop-42"
  author = ""

[global]
  plan = "libp2p/ping"
  case = "ping"
  runner = "local:docker"

  [global.build_config]
    enable_go_build_cache = false
    go_proxy_mode = "remote"
    go_proxy_url = "https://proxy.golang.org"

[[groups]]
  id = "rust-master"
  builder = "docker:generic"
  [groups.build_config]
    path = "./rust/"
    [groups.build_config.build_args]
      CARGO_FEATURES = "libp2pmaster"
      RUN_ID = "42"
      RUST_LIBP2P_MASTER_SHA = "eb10af7"

[[groups]]
  id = "rust-v0.47.0"
  builder = "docker:generic"
  [groups.build_config]
    path = "./rust/"
    [groups.build_config.build_args]
      CARGO_FEATURES = "libp2pv0470"
      RUN_ID = "42"
      RUST_LIBP2P_MASTER_SHA = "eb10af7"

[[groups]]
  id = "go-master"
  builder = "docker:go"
  [groups.build_config]
    build_base_image = "golang:1.18-buster"
    modfile = "go.v0.22.mod"
    path = "./go/"
    [groups.build_config.dockerfile_extensions]
      pre_build = "RUN cd ${PLAN_DIR} && go mod download github.com/libp2p/go-libp2p && go mod tidy -compat=1.18        "
  [groups.build]
    selectors = ["v0.22"]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p"
      target = ""
      version = "63b8803"

[[groups]]
  id = "go-v0.22"
  builder = "docker:go"
  [groups.build_config]
    build_base_image = "golang:1.18-buster"
    modfile = "go.v0.22.mod"
    path = "./go/"
  [groups.build]
    selectors = ["v0.22"]

[[runs]]
  id = "rust-master x rust-v0.47.0 x 1 iteration"

  [runs.test_params]
    iterations = "1"

  [[runs.groups]]
  id = "rust-master"
  instances = { count = 1}

  [[runs.groups]]
  id = "rust-v0.47.0"
  instances = { count = 1}

[[runs]]
  id = "rust-master x rust-v0.47.0 x 5 iteration"

  [runs.test_params]
    iterations = "5"

  [[runs.groups]]
  id = "rust-master"
  instances = { count = 1}

  [[runs.groups]]
  id = "rust-v0.47.0"
  instances = { count = 1}

[[runs]]
  id = "rust-master x go-master x 1 iteration"

  [runs.test_params]
    iterations = "1"

  [[runs.groups]]
  id = "rust-master"
  instances = { count = 1}

  [[runs.groups]]
  id = "go-master"
  instances = { count = 1}
