name = "webrtc:go"

[builders]
"exec:go"   = { enabled = true }

[builders."docker:go"]
enabled                = true
build_base_image       = "golang:1.19-bullseye"

[runners]
"local:docker"  = { enabled = true }

[[testcases]]
name = "ping"
instances = { min = 1, max = 10000, default = 1 }

  [testcases.params]
  secure_channel    = { type = "enum", desc = "secure channel used", values = ["noise", "tls"], default = "noise" }
  max_latency_ms    = { type = "int", desc = "maximum value for random local link latency", unit = "ms", default = 1000 }
  iterations        = { type = "int", desc = "number of ping iterations we'll run against each peer", unit = "count", default = 2 }
