[master]
GoVersion = '1.18'
Modfile = "go.v0.22.mod"
Selector = 'v0.22'

[custom]
GoVersion = '1.18'
Modfile = "go.v0.22.mod"
Selector = 'v0.22'

[[groups]]
Id = "v0.22"
GoVersion = '1.18'
Modfile = "go.v0.22.mod"
Selector = 'v0.22'

[[groups]]
Id = "v0.21"
GoVersion = '1.18'
Modfile = "go.v0.21.mod"
Selector = 'v0.21'

[[groups]]
Id = "v0.20"
GoVersion = '1.18'
Modfile = "go.v0.20.mod"
Selector = 'v0.20'

[[groups]]
Id = "v0.19"
GoVersion = '1.17'
Modfile = "go.v0.19.mod"
Selector = 'v0.19'

